### ISSUE TITLE
Synthetic event generation from Human3.6m 

### ISSUE THREAD

**Issue by asudeeaydin** [IIT-PAVIS/lifting_events_to_3d_hpe#5]
Hi, 

I'm trying to generate synthetic events from the Human3.6m dataset using the event_library repo. However, I'm getting hydra errors and haven't been able to fix the issue. Is it possible to generate this dataset directly by using the vid2e repo from RPG? Are there any differences between your library and their implementation?

**Comment by gianscarpe** [comment]
Hi @asudeeaydin! Yes, you should be able to generate data directly using RPG's vid2e, although I cannot guarantee. My implementation is a wrapper around RPG's code. Hope it helps!
