### ISSUE TITLE
pretrained models?

### ISSUE THREAD

**Issue by tlwzzy** [IIT-PAVIS/lifting_events_to_3d_hpe#6]
Hi, thanks for the great work.

In the link you give [this link](https://drive.google.com/drive/folders/1b5BTt4A8kRGPAVwZ2HY1RKoMQ54lPsGZ?usp=sharing) i found that in all xxx\checkpoints\ are just empty or a single auc.json. 

Is that a bug?Or can you tell me how to download the pretrained checkpoints to directly inference?

Thanks anyways.

**Comment by pmorerio** [comment]
Right.
@gianscarpe any issue with google drive?

**Comment by ming-lab121** [comment]
Do you have the pretrained checkpoints？

**Comment by gianscarpe** [comment]
Hi! Unfortunately not anymore I'm sorry. It shouldn't be too hard to re-train tho
